favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://etalon.ryazanszn.ru/themes/blondytan2/favicon.ico'
  use_default: 1
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://logo.png'
  url: ''
  use_default: 0
breadcrumb_home: 1
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
  footer_left: ''
  footer_middle: ''
  footer_right: ''
image_responsive: 0
modal_enabled: 0
second_text: ''
breadcrumb_title: 1
schemas:
  blondytan2: 8000
  bootstrap: 8000
schema: 8000
table_responsive: '-1'
table: ''
langcode: ru
