minimum_single: 20
minimum_multiple: 20
disable_search_threshold: 0
minimum_width: 0
use_relative_width: false
jquery_selector: 'select:visible'
search_contains: false
disable_search: false
allow_single_deselect: false
placeholder_text_multiple: 'Выберите какие-нибудь варианты'
placeholder_text_single: 'Выберите вариант'
no_results_text: 'Нет соответствий'
max_shown_results: null
disabled_themes:
  seven: '0'
  blondytan2: '0'
  bootstrap: '0'
chosen_include: 0
_core:
  default_config_hash: exRaKE0s6uZbfQrl_2WFEcTlc_1t81xEqCLuCCteUSk
langcode: ru
