_core:
  default_config_hash: 6Wk4BLqlH9PdR3lPJohO4Ek3-uRJAgdfrVT4qWYXVMY
langcode: ru
abs_urls: false
admin_theme: false
roles_profiles:
  administrator:
    public: admin
  editor:
    public: member
