_core:
  default_config_hash: d-bH3--ktq6mwN7d37KW59P77RS2YPh2ybgA7kAwfTU
template_key: site_settings
loader_plugin: full
disable_auto_loading: false
hide_description: true
hide_advanced: true
hide_group: true
simple_summary: true
show_groups_in_menu: true
