_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
langcode: ru
smtp_on: true
smtp_host: scp111.hosting.reg.ru
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_autotls: true
smtp_timeout: 30
smtp_username: feedback@u1005861.cp.regruhosting.ru
smtp_password: 6LcXkJMUAAAAA
smtp_from: feedback@ryazanszn.ru
smtp_fromname: 'Служба уведомлений портала ryazanszn.ru'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: false
smtp_test_address: ''
smtp_reroute_address: ''
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: false
smtp_debug_level: 1
