_core:
  default_config_hash: pfrv6lPS72f5WG1UB4wHkgQV2invlHwVpaCy_mY-ClQ
langcode: ru
enable_globally: null
enable_globally_on_admin_routes: false
default_challenge: recaptcha/reCAPTCHA
description: 'Этот вопрос задается для того, чтобы выяснить, являетесь ли Вы человеком или представляете из себя автоматическую спам-рассылку.'
title: CAPTCHA
administration_mode: false
administration_mode_on_admin_routes: false
default_validation: 1
persistence: 1
enable_stats: false
log_wrong_responses: false
