favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://ryazanszn.ru/themes/blondytan2pe/favicon.ico'
  use_default: 1
schema: '8000'
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: ''
  url: ''
  use_default: 1
cdn_provider: ''
breadcrumb_home: 1
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: well
  footer: ''
  footer_left: ''
  footer_middle: ''
  footer_right: ''
image_responsive: 0
