favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'https://ryazanszn.ru/themes/blondytan2/favicon.ico'
  use_default: 0
schemas:
  bootstrap: 8000
  blondytan2: 8000
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://logo.png'
  url: ''
  use_default: 0
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: 'well well-sm'
  footer: ''
  footer_left: ''
  footer_middle: ''
  footer_right: ''
image_responsive: 0
second_text: ''
breadcrumb_home: 1
modal_enabled: 0
cdn_theme: ''
cdn_cache_ttl_versions: 0
cdn_cache_ttl_themes: 0
cdn_cache_ttl_assets: 0
cdn_cache_ttl_library: 0
reset_http_request_cache: ''
table: ''
langcode: ru
