_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
module:
  admin_toolbar: 0
  automated_cron: 0
  block: 0
  block_content: 0
  bootstrap_library: 0
  breakpoint: 0
  captcha: 0
  chosen: 0
  chosen_lib: 0
  ckeditor5: 0
  colorbox: 0
  comment: 0
  config: 0
  config_filter: 0
  config_split: 0
  contact: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  imce: 0
  language: 0
  link: 0
  locale: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  phpass: 0
  recaptcha: 0
  recreate_block_content: 0
  search: 0
  shortcut: 0
  sitemap: 0
  smtp: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  update: 0
  user: 0
  views_bootstrap: 0
  views_extras: 0
  views_field_view: 0
  views_tree: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  bootstrap: 0
  blondytan2: 0
  claro: 0
profile: standard
