_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: ru
uuid: 7b5edf11-5cc7-40da-954e-38be12946a68
name: 'Портал министерства труда и социальной защиты населения'
mail: s.dev.ap@yandex.ru
slogan: 'Рязанская область'
page:
  403: ''
  404: ''
  front: /node/2
admin_compact_mode: false
weight_select_max: 100
default_langcode: ru
mail_notification: ''
