favicon:
  mimetype: image/vnd.microsoft.icon
  path: themes/blondytan2/favicon.ico
  url: 'http://ard-pni.ryazanszn.ru/themes/blondytan2/favicon.ico'
  use_default: 1
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 0
  node_user_picture: 1
logo:
  path: 'public://logo.png'
  url: ''
  use_default: 0
breadcrumb_home: 1
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
  footer_left: ''
  footer_middle: ''
  footer_right: ''
image_responsive: 0
modal_enabled: 0
second_text: ''
schemas:
  bootstrap: 8000
  blondytan2: 8000
table_responsive: '-1'
table: ''
cdn_theme: ''
cdn_cache_ttl_versions: 0
cdn_cache_ttl_themes: 0
cdn_cache_ttl_assets: 0
cdn_cache_ttl_library: 0
reset_http_request_cache: ''
langcode: ru
