_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
langcode: ru
mode: simple
ignored_config_entities:
  - 'contact.form.feedback:recipients'
  - system.site
  - views.settings
  - 'xmlsitemap.xmlsitemap.*'
